# Generated by Django 6.0.1 on 2026-02-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_payment_rental_and_more'),
        ('rentals', '0002_remove_rental_is_active_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental'),
        ),
    ]
