# Generated by Django 6.0.1 on 2026-03-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_rental'),
        ('rentals', '0005_rentalitem_available_from_rentalitem_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rentalitem'),
        ),
    ]
