# Generated by Django 6.0.1 on 2026-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalitem_alter_rental_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
