# Generated by Django 6.0.1 on 2026-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalitem_available_from_rentalitem_available_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='show_owner_name',
            field=models.BooleanField(default=False),
        ),
    ]
