# Generated by Django 6.0.1 on 2026-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_renter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='item_type',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle'), ('house', 'House'), ('item', 'Item')], help_text='Specifies what type of items the renter offers.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('renter', 'Renter')], default='renter', help_text='Defines whether the user is an Owner or Renter.', max_length=20),
        ),
    ]
