# Generated by Django 6.0.1 on 2026-03-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
