# Generated by Django 6.0.1 on 2026-03-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='show_owner_name',
            field=models.BooleanField(default=False),
        ),
    ]
